[package]
name = "burst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1"
odds = { version = "0.4.0", features = ["std-vec"] }

[profile.release]
debug = true

